import type { MigrationInterface, QueryRunner } from 'typeorm';

/** F1 products and F2 inventory (single warehouse, movement history). */
export class CreateProductsAndInventory1790000000000 implements MigrationInterface {
  name = 'CreateProductsAndInventory1790000000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE products (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sku varchar(64) NOT NULL,
        name varchar(200) NOT NULL,
        price integer NOT NULL,
        sales_status varchar(20) NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT uq_products_sku UNIQUE (sku),
        CONSTRAINT ck_products_price CHECK (price >= 0),
        CONSTRAINT ck_products_sales_status CHECK (sales_status IN ('on_sale', 'discontinued'))
      )
    `);
    await queryRunner.query(`
      CREATE TABLE inventory_items (
        product_id integer PRIMARY KEY REFERENCES products (id),
        quantity integer NOT NULL DEFAULT 0,
        updated_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT ck_inventory_items_quantity CHECK (quantity >= 0)
      )
    `);
    await queryRunner.query(`
      CREATE TABLE stock_movements (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product_id integer NOT NULL REFERENCES products (id),
        type varchar(10) NOT NULL,
        reason varchar(20) NOT NULL,
        quantity integer NOT NULL,
        balance_after integer NOT NULL,
        order_id integer,
        note varchar(200),
        created_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT ck_stock_movements_type CHECK (type IN ('in', 'out')),
        CONSTRAINT ck_stock_movements_reason CHECK (reason IN ('goods_in', 'goods_out', 'order')),
        CONSTRAINT ck_stock_movements_quantity CHECK (quantity > 0),
        CONSTRAINT ck_stock_movements_balance CHECK (balance_after >= 0)
      )
    `);
    await queryRunner.query(
      'CREATE INDEX ix_stock_movements_product_created ON stock_movements (product_id, created_at DESC)',
    );
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE stock_movements');
    await queryRunner.query('DROP TABLE inventory_items');
    await queryRunner.query('DROP TABLE products');
  }
}
