import type { MigrationInterface, QueryRunner } from 'typeorm';

/** F3 customers. */
export class CreateCustomers1790000001000 implements MigrationInterface {
  name = 'CreateCustomers1790000001000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE customers (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(100) NOT NULL,
        address varchar(200) NOT NULL,
        phone varchar(20) NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now()
      )
    `);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE customers');
  }
}
