import type { MigrationInterface, QueryRunner } from 'typeorm';

/** F4 orders with lines. Stock movements of type `order` point to their order. */
export class CreateOrders1790000002000 implements MigrationInterface {
  name = 'CreateOrders1790000002000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('CREATE SEQUENCE order_number_seq');
    await queryRunner.query(`
      CREATE TABLE orders (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_number varchar(20) NOT NULL,
        customer_id integer NOT NULL REFERENCES customers (id),
        status varchar(10) NOT NULL,
        total_amount integer NOT NULL,
        ordered_at timestamptz NOT NULL DEFAULT now(),
        shipped_at timestamptz,
        CONSTRAINT uq_orders_order_number UNIQUE (order_number),
        CONSTRAINT ck_orders_status CHECK (status IN ('受付', '出荷済')),
        CONSTRAINT ck_orders_total_amount CHECK (total_amount >= 0)
      )
    `);
    // Owned by the column: dropped with the table and restarted by TRUNCATE … RESTART IDENTITY.
    await queryRunner.query('ALTER SEQUENCE order_number_seq OWNED BY orders.order_number');
    await queryRunner.query('CREATE INDEX ix_orders_customer ON orders (customer_id)');
    await queryRunner.query('CREATE INDEX ix_orders_ordered_at ON orders (ordered_at DESC)');
    await queryRunner.query(`
      CREATE TABLE order_lines (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id integer NOT NULL REFERENCES orders (id),
        product_id integer NOT NULL REFERENCES products (id),
        quantity integer NOT NULL,
        unit_price integer NOT NULL,
        line_amount integer NOT NULL,
        CONSTRAINT uq_order_lines_product UNIQUE (order_id, product_id),
        CONSTRAINT ck_order_lines_quantity CHECK (quantity > 0),
        CONSTRAINT ck_order_lines_unit_price CHECK (unit_price >= 0)
      )
    `);
    await queryRunner.query(`
      ALTER TABLE stock_movements
        ADD CONSTRAINT fk_stock_movements_order FOREIGN KEY (order_id) REFERENCES orders (id)
    `);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('ALTER TABLE stock_movements DROP CONSTRAINT fk_stock_movements_order');
    // The orders are dropped; keep the stock history (and its balances) but drop the links.
    await queryRunner.query('UPDATE stock_movements SET order_id = NULL WHERE order_id IS NOT NULL');
    await queryRunner.query('DROP TABLE order_lines');
    await queryRunner.query('DROP TABLE orders'); // also drops the owned order_number_seq
  }
}
